project:
  type: website

website:
  title: "Posit Docs"
  favicon: logos/favicon.svg
  bread-crumbs: true
  back-to-top-navigation: true
  cookie-consent:
    type: express
    style: interstitial
    policy-url: https://posit.co/privacy
  page-navigation: true
  navbar:
    logo: logos/posit-icon-fullcolor.svg
    left:
      - text: Home
        href: index.qmd
      - text: Guides
        menu:
          - text: Admin
            href: guides/admin.qmd
          - text: User Guide
            href: guides/user.qmd
    right:
      - text: docs.posit.co
        href: https://docs.posit.co
      - text: Posit Support
        href: https://support.posit.co/hc/en-us/
      - text: Products
  sidebar:
    - title: "Admin Guide"
      contents:
        - guides/admin.qmd
        - section: Subsection
          contents:
            - text: Installation
              file: install.qmd
            - text: Duplicate
              file: install.qmd
        - section: Subsection
          contents:
            - text: Installation
              file: install.qmd
            - text: Duplicate
              file: user.qmd
            - text: Duplicate
              file: install.qmd

    - title: "User Guide"
      contents:
        - guides/user.qmd
        - section: Subsection
          contents:
            - text: Sharing
              file: sharing.qmd
            - text: Duplicate
              file: sharing.qmd
  page-footer:
    left: |
      Copyright &copy; 2000-2025 Posit Software, PBC. All Rights Reserved.
    center: |
      Posit PRODUCT 12345
    right:
      - icon: question-circle-fill
        aria-label: 'Link to Posit Support'
        href: "https://support.posit.co/hc/en-us"
      - text: '<a href="#" id="open_preferences_center" title="Manage your cookie preferences"><i class="bi bi-cookie"></i></i></a>'
        aria-label: 'Cookie Prefs'
      - text: "<img alt='Link to main Posit site' src='/assets/images/posit-icon-fullcolor.svg' id='footer-right-posit-logo'>"
        href: "https://posit.co/"

format:
  html:
    theme: 
      light: [brand, styles.scss]
      dark: [brand, theme-dark.scss]
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    highlight-style: github
    grid:
      sidebar-width: 300px



