project:
  type: website

website:
  title: "Posit Docs"
  favicon: logos/favicon.svg
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Admin Guide"
        file: admin.qmd
      - text: "User Guide"
        file: user.qmd
    right:
      - text: "docs.posit.co"
        href: "https://docs.posit.co"
      - text: "Posit Support"
        href: "https://support.posit.co/hc/en-us/"
  sidebar:
    - title: "Admin Guide"
      contents:
        - admin.qmd
        - section: Subsection
          contents:
            - text: Installation
              file: install.qmd
            - text: Duplicate
              file: install.qmd
        - section: Subsection
          contents:
            - text: Installation
              file: install.qmd
            - text: Duplicate
              file: install.qmd
            - text: Duplicate
              file: install.qmd

    - title: "User Guide"
      contents:
        - user.qmd
        - section: Subsection
          contents:
            - text: Sharing
              file: sharing.qmd
            - text: Duplicate
              file: sharing.qmd
  page-footer:
    left: |
      Copyright &copy; 2000-2025 Posit Software, PBC. All Rights Reserved.
    center: |
      Posit PRODUCT 12345

format:
  html:
    theme: [brand, styles.scss]
    toc: true
    link-external-icon: true
    link-external-newwindow: true



